name: Terraform Apply
on:
  push:

jobs:
  Terraform:
    defaults:
      run:
        working-directory: "./test"

    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        env:
          service_account: "github@liatrio-mission-368815.iam.gserviceaccount.com"

      - name: 'Set  up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: 'Terraform Init'
        id: init
        run: terraform init
        working-directory: "examples/"

      - name: Terraform apply and test verification
        id: apply
        env:
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
        run: go test -v -timeout 120m

